# Generated by Django 4.1.6 on 2023-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdatamodel",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
