# Generated by Django 4.1.6 on 2023-02-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_userprofilemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdatamodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="blog_data_model_likes",
                to="blog.userdetailsmodel",
            ),
        ),
    ]
