# Generated by Django 4.1.6 on 2023-02-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogdatamodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdatamodel",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="blogdatamodel",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
