# Generated by Django 4.1.6 on 2023-02-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogdatamodel_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("create_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="blogdatamodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="blog_data_model_likes",
                to="blog.userdetailsmodel",
            ),
        ),
        migrations.AddField(
            model_name="blogdatamodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_category",
                to="blog.blogcategorymodel",
            ),
        ),
    ]
