# Generated by Django 4.1.6 on 2023-02-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogcategorymodel_alter_blogdatamodel_likes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileFieldModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_field", models.FileField(upload_to="media/files/")),
            ],
        ),
    ]
