# Generated by Django 4.1.6 on 2023-02-17 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_filefieldmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filefieldmodel",
            name="file_field",
            field=models.FileField(
                upload_to="media/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
