# Generated by Django 4.1.6 on 2023-02-17 06:07

import blog.filevalidations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_filefieldmodel_file_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filefieldmodel",
            name="file_field",
            field=models.FileField(
                upload_to="media/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "mp4"]
                    ),
                    blog.filevalidations.validate_file_size,
                ],
            ),
        ),
    ]
