# Generated by Django 4.1.6 on 2023-02-17 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0010_blogdatamodel_author_alter_blogdatamodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdatamodel",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
